name: de-project-vinson

on:
  push:
    branches:
      - '**'
    #Terraform will be deployed once changes happening in these paths
    paths:
      - 'terraform/**'
      - 'packages/**'
      - 'src/extract/extract.py'
      - 'src/transform/transform.py'

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create requirements
        run: make requirements
      - name: Run Dev Setup
        run: make dev-setup
      - name: Run All Checks
        run: make run-checks


  deploy-terraform:
    name: deploy-terraform
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    #Trigger if only changes in the main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}    
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve
      